@ECHO OFF
REM Compile and link all .BAS files. 
REM Uses CALL CL.BAT to carry out the process.
REM All compiler and linker options set in CL.BAT
REM RBK 7/9/95
CALL CL TREEH1
CALL CL TREEH2
CALL CL TREE2
CALL CL TREE3
CALL CL SIER
CALL CL COMB
CALL CL KOCH
CALL CL MINK
CALL CL MEANDER
CALL CL LEVY
CALL CL DRAGON
CALL CL DRAGON0
CALL CL DRAGON1
CALL CL UNWIND
CALL CL ARCH1
CALL CL LOGSPIRA
CALL CL SPHERSPI
CALL CL WHIRL
CALL CL PYTHT1
CALL CL PYTHT2
CALL CL PYTHT3
CALL CL PYTHTB
CALL CL TREEM
CALL CL STAR
CALL CL DUSTB
CALL CL DUSTBT
CALL CL MONDRIAN
CALL CL DUST
CALL CL PYTHTD
CALL CL BROWNL
CALL CL COLLET
CALL CL HENON
CALL CL MIRA
CALL CL JULIAB
CALL CL MANDEL
CALL CL CLOUD
CALL CL CLOUD1
CALL CL CLOUD2
CALL CL DUSTV
CALL CL MEANDERN
CALL CL MEANDERB
CLS
ECHO.
ECHO.
ECHO  Finished compiling and linking
ECHO.
ECHO.
